kind: pipeline
name: default

steps:
  - name: install
    image: harbor.patozon.net/library/web/node
    commands:
      - npm config set registry https://registry.npm.taobao.org
      - npm cache clean --force
      - npm i
      - sed -i 's:self.xhr.send(payload);://self.xhr.send(payload);:' ./node_modules/sockjs-client/dist/sockjs.js
      - npm run build
    when:
      ref:
        - refs/tags/*

  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: harbor.patozon.net/library/web/pmweb
      insecure: true
      tag: ${DRONE_TAG=latest}
      registry: harbor.patozon.net
      dockerfile: ./Dockerfile
    when:
      ref:
        - refs/tags/*

  - name: k8s-test
    image: vallard/drone-kube
    environment:
      DRONE_TAG: ${DRONE_TAG=latest}
    settings:
      template: deployment.yaml
      namespace: permission
      server:
        from_secret: test_kube_server
      token:
        from_secret: test_kube_token
      ca:
        from_secret: test_kube_ca
    when:
      ref:
        - refs/tags/test-*

  - name: k8s-prod
    image: vallard/drone-kube
    settings:
      template: deployment.yaml
      namespace: permission
      server:
        from_secret: prod_kube_server
      token:
        from_secret: prod_kube_token
      ca:
        from_secret: prod_kube_ca
    when:
      ref:
        - refs/tags/prod-*

  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token: 464046b72e351fe5e9c7aa34a3f13ef0e5ddeaface1ce6fd79478512206657a5
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status:
        - success
        - failure

trigger:
  when:
    ref:
      - refs/tags/*