  # Use root/example as user/password credentials
version: '3'

services:
  node:
    restart: always
    image: node:alpine
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    volumes:
      - ./:/data
    working_dir: /data
    command: ['npm','run','dev']